### ISSUE TITLE
ATTRIBUTES - Booted out when trying to delete generated attributes

### ISSUE THREAD

**Issue by Allison-Labbrand** [ms8909/labbrand-frontend#14]
@muz786
Priority: Med
Issue Type: Code
Description: Doesn't happen when I try to delete an attribute I input myself, only with generated attributes.
Device, Browser: MacBook, Chrome
URL: http://namelab.labbrand.co/dashboard/2

**Comment by muz786** [comment]
I have disabled the option to delete generated attributes as the related api is not implemented.

**Comment by Allison-Labbrand** [comment]
@ms8909 can we develop that?

**Comment by Allison-Labbrand** [comment]
@ms8909 I see this has been disabled. Will the design created by @muz786 still be there once enabled?
