### ISSUE TITLE
CANCEL button position

### ISSUE THREAD

**Issue by Kerwin00** [ms8909/labbrand-frontend#21]
Issue Type: Design
Description: For all pages when have pop-up editable window, if we have a CANCEL button, it should stay on the left side, cause from UX point of view user usually feel the left side button is not more important than the right side button, see attached screenshot.
Device, Browser: iMac, Chrome
<img width="1438" alt="WX20190816-180038@2x" src="https://user-images.githubusercontent.com/46305926/63161651-2a89c000-c053-11e9-972f-a6d6f64fe271.png">

**Comment by Allison-Labbrand** [comment]
To clarify, the SAVE and CANCEL buttons should switch places.

**Comment by Allison-Labbrand** [comment]
This is an issue in a number of touchpoints. @muz786  Could you check that each page has the action on the right, CANCEL on the left? A couple examples below.
![Screen Shot 2019-08-26 at 10 17 20 AM](https://user-images.githubusercontent.com/53892848/63685161-37679a00-c831-11e9-902b-f0b73167e000.png)
![Screen Shot 2019-08-26 at 10 18 45 AM](https://user-images.githubusercontent.com/53892848/63685162-38003080-c831-11e9-91ff-72fb8d27bd12.png)

**Comment by muz786** [comment]
@Allison-Labbrand fixed

**Comment by Allison-Labbrand** [comment]
@muz786 not yet fixed.
![Screen Shot 2019-09-03 at 6 04 33 PM](https://user-images.githubusercontent.com/53892848/64164474-ea5d7680-ce75-11e9-9929-e32795743b7f.png)

**Comment by Allison-Labbrand** [comment]
![Screen Shot 2019-09-03 at 6 45 15 PM](https://user-images.githubusercontent.com/53892848/64168995-5b555c00-ce7f-11e9-9abb-db032fc06cda.png)
