### ISSUE TITLE
GENERATE page go to FAVORITES

### ISSUE THREAD

**Issue by Kerwin00** [ms8909/labbrand-frontend#25]
Issue Type: Design
Description: When finish GENERATE step and hover the FAVORITE, there should be an arrow icon appears, as a visual guide to click on it and go to FAVORITE page, see screenshot.
<img width="2447" alt="WX20190816-185137@2x" src="https://user-images.githubusercontent.com/46305926/63163154-252e7480-c057-11e9-886b-ada4409eb7a6.png">
Device, Browser: iMac, Chrome

**Comment by ms8909** [comment]
@muz786 Can you add an arrow.

**Comment by Allison-Labbrand** [comment]
@muz786 really sorry I'm just seeing this. Could you put it back to match the others, with just the line below it? The arrow is quite distracting from Labbrand's design.
