### ISSUE TITLE
LONGLIST - retain one un-deletable list

### ISSUE THREAD

**Issue by Allison-Labbrand** [ms8909/labbrand-frontend#27]
@ms8909 
Priority: Med
Issue Type: Code
Device, Browser: MacBook, Chrome
URL: http://namelab.labbrand.co/dashboard/2
Detail: The first list should never be able to be deleted. If I delete that, then I can't input individual names anymore, only excel uploads.

**Comment by ms8909** [comment]
Done. Just need to test this
