### ISSUE TITLE
FAVOURITES - When I move anything into LOVE IT, TM becomes Red

### ISSUE THREAD

**Issue by Allison-Labbrand** [ms8909/labbrand-frontend#44]
@muz786 @ms8909 
Priority: Med
Issue Type: Design/Code
Device, Browser: MacBook, Chrome
QUESTION: At what point will TM's be checked, from a coding perspective?

![Screen Shot 2019-08-23 at 7 36 22 PM](https://user-images.githubusercontent.com/53892848/63590051-5110a380-c5dd-11e9-8709-ca34f2115697.png)

**Comment by ms8909** [comment]
@muz786 Let's add the API in the front-end. 

@Allison-Labbrand I have not finished the TM code yet. Fixing all the bugs in the backend is taking all the time.
