### ISSUE TITLE
FAVOURITES/GENERATE - LOVE IT, LIKE IT, NOT THIS TIME should all stay in LIKE IT on GENERATE page

### ISSUE THREAD

**Issue by Allison-Labbrand** [ms8909/labbrand-frontend#45]
@ms8909 
Priority: HIGH
Issue Type: Code
Device, Browser: MacBook, Chrome
Detail: All names in Love it, like it, not this time should still appear in list on GENERATE page under LIKE IT. Currently, when I move a name to Love it or Not this time, it disappears from the LIKE IT column on GENERATE page.
![Screen Shot 2019-08-23 at 7 20 09 PM](https://user-images.githubusercontent.com/53892848/63590142-97660280-c5dd-11e9-9297-42bbc4829f38.png)

**Comment by ms8909** [comment]
Done. Just need to check

**Comment by Allison-Labbrand** [comment]
@ms8909 
On the FAVOURITES page, the names moved to LOVE IT or NOT THIS TIME should NOT show up in LIKE IT. However, on GENERATE page, names from all lists (like, love, not this time), should all show up in LIKE IT.

**Comment by Allison-Labbrand** [comment]
@ms8909 this issue is happening again.
