### ISSUE TITLE
FAVOURITES EXCEL - See attached

### ISSUE THREAD

**Issue by Allison-Labbrand** [ms8909/labbrand-frontend#46]
@ms8909 
Priority: HIGH
Issue Type: Code
Device, Browser: MacBook, Chrome
Details:
• Let’s please add Not this time as a type into the downloaded excel 
• Numbers on left should start at 1
• Can we add a column reflecting the legal risk for each name, with heading “TM RISK”. Other heading should also be capitalized
• Document title should reflect PROJECT NAME_session name if possible. Otherwise, all can be Namelab Favourites, rather than “t”

**Comment by ms8909** [comment]
Not this time added to the list. Just need to test this

**Comment by Allison-Labbrand** [comment]
@ms8909 
• Numbers should start at 1, not 0.
• only some names show result for TM risk
• can we change doc title?
