### ISSUE TITLE
ATTRIBUTES - Can't generate

### ISSUE THREAD

**Issue by Allison-Labbrand** [ms8909/labbrand-frontend#49]
@ms8909 
Priority: Med
Issue Type: Code
Device, Browser: MacBook, Chrome
![Screen Shot 2019-08-08 at 5 33 31 PM](https://user-images.githubusercontent.com/53892848/63590689-2a536c80-c5df-11e9-8ac4-15ead1f6a68c.png)

**Comment by ms8909** [comment]
Please try again if this error comes
