### ISSUE TITLE
SCROLLBAR - press enter after typing in page number to GO

### ISSUE THREAD

**Issue by Allison-Labbrand** [ms8909/labbrand-frontend#53]
@ms8909 @muz786 
Issue type: Design/Code
![Screen Shot 2019-08-27 at 7 06 20 PM](https://user-images.githubusercontent.com/53892848/63766531-ec678880-c8fd-11e9-8908-453c9b6c394e.png)

**Comment by Allison-Labbrand** [comment]
@muz786 the navigation bar from one page to the next in a long list is gone it seems?

**Comment by muz786** [comment]
@Allison-Labbrand are you talking about pagination? Pagination is working on long list. can you confirm?

**Comment by Allison-Labbrand** [comment]
@muz786 
![Screen Shot 2019-09-04 at 10 45 10 AM](https://user-images.githubusercontent.com/53892848/64222824-1a535b00-cf04-11e9-8271-70e524a5bc01.png)

**Comment by muz786** [comment]
@Allison-Labbrand fixed
