### ISSUE TITLE
SCROLLBAR issue

### ISSUE THREAD

**Issue by Allison-Labbrand** [ms8909/labbrand-frontend#60]
@muz786 

On both GENERATE - CREATE column and ATTRIBUTES pages, the page content often isn't maxed out, yet it doesn't fill fully with words. 

When I navigate to another page and back on ATTRIBUTES, it fills up. 

However, on GENERATE - CREATE's list, it's just not filled with all I should be able to scroll through. A page only extends when I add new names directly to that page.

**Comment by ms8909** [comment]
Can you explain this a bit @Allison-Labbrand 
"However, on GENERATE - CREATE's list, it's just not filled with all I should be able to scroll through. A page only extends when I add new names directly to that page"

**Comment by Allison-Labbrand** [comment]
@ms8909 @muz786 The problem is not that CREATE names can't flip from one page to the next, but rather that users can't scroll through the 50 or however many names the user should be able to scroll through without flipping pages. This forces a lot of slow page-flipping.

**Comment by Allison-Labbrand** [comment]
https://we.tl/t-PiAsOkoWHG see here for video.

**Comment by muz786** [comment]
@Allison-Labbrand i have increased the page size limit to 50.

**Comment by Allison-Labbrand** [comment]
Looks good.

 

Allison Rose

Senior Consultant

 

We drive forward the positive power of branding. 
Learn more about our work and perspectives.

 

Labbrand Brand Innovations 

 

T  +86 21 62988956  |  M  +86 156 01633984

E  allison.rose@labbrand.com

 

Shanghai | Paris | New York | Singapore

 

labbrand.com
